name: Build Docker images

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish to Github Docker registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: robinj1995/totaleblindheidbot/totale-blindheid-bot
          registry: ghcr.io
          username: RobinJ1995
          password: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          snapshot: true
      - name: Trigger deployment
        if: ${{ success() }}
        run: |
          curl -sS --fail -X PUT -H "Authorization: Bearer ${{ secrets.KUBECONTROL_TOKEN }}" https://kuber0.robinj.be/deployment/telegram-bots/totale-blindheid